### ISSUE TITLE
Require `tty/which` and `tty/screen`

### ISSUE THREAD

**Issue by RyanScottLewis** [piotrmurach/tty-pager#1]
They are dependencies, but not required in the library. I had to require them in my script before being able to use TTY::Pager.

**Comment by piotrmurach** [comment]
Both dependencies are required in [lib/tty-pager.rb](https://github.com/piotrmurach/tty-pager/blob/master/lib/tty-pager.rb). I've just double checked installing `tty-pager` in clean environment and things work fine. Not sure how you required the library? It makes me wonder given the title of this issue and the lack of dependencies that you used `require 'tty/pager'` which obviously wouldn't work. Can you try `require 'tty-pager'` instead.

**Comment by RyanScottLewis** [comment]
That's exactly what happened. -_- Sorry bout that! Hah
