### ISSUE TITLE
Consider restructuring tests for ease of maintenance

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/tty-pager#18]
Specs can be restructured to be per-class rather than per-method.

**Comment by piotrmurach** [comment]
@AndrewRadev Wonder if you still want to take a look at this? No worries if you don't have time or don't want to. I thought you may enjoy refactoring the tests and suggesting a new layout/structure. My plan is to release this in the next week or so provided all issues are addressed as I think the recent changes make this gem so much better.

**Comment by AndrewRadev** [comment]
I would like to, but as you say, it's a matter of time. I'm planning to try writing integration tests over this weekend (although we'll see how it goes in terms of time), and I could do this in the process maybe.

**Comment by piotrmurach** [comment]
There is a separate issue for integration tests and these would be a great addition. I'm currently increasing test coverage and in doing so found couple of small issues/bugs with BasicPager so I will focus on fixing these and potentially refactoring some of the behaviour. This gem is part of 15 tty gems that I need to prepare for a new release of the `tty` gem. There is no pressure to get this one done first. I have plenty to do anyhow. I much appreciate all the help you've provided so far.
