### ISSUE TITLE
Doesn't play nicely with piped git pagers

### ISSUE THREAD

**Issue by JacobEvelyn** [piotrmurach/tty-pager#2]
I'd love to incorporate `tty-pager` into a [CLI program](https://github.com/JacobEvelyn/friends) I'm working on, but my default `git` pager is set to [`diff-so-fancy`'s recommendation](https://github.com/so-fancy/diff-so-fancy#usage) of `"diff-so-fancy | less --tabs=4 -RFX"`.

`tty-pager` isn't smart enough to process that and use `tty-which` on `diff-so-fancy` and `less`. Would you be interested in incorporating that change if I made a PR for it?

**Comment by piotrmurach** [comment]
I'm all for `tty-pager` to play nicely! Please see my PR comments.

**Comment by JacobEvelyn** [comment]
Thanks so much for merging this! If you could let me know when you've released a new gem version so I can use this that would be wonderful. :)

**Comment by piotrmurach** [comment]
Released `v0.6.0`. Enjoy!
