### ISSUE TITLE
ruby 3.1.0p0 issue with Gem v3.3.3

### ISSUE THREAD

**Issue by edk** [piotrmurach/tty-pager#27]
### Describe the problem

Trying to use tty in latest ruby 3.1.0p0 and get an error.  I'm coming back to ruby after a long break and so this may be obvious or I may have missed something, sorry if that's the case!

```
$ ruby test.rb
require 'tty-pager' failed with undefined method `gunzip' for Gem:Module

    INDEX = Marshal.load(Gem.gunzip(File.binread(INDEX_FILENAME)))
```

### Steps to reproduce the problem

Simple ruby file:
```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'tty'
  gem 'tty-screen'
end
```
run with ruby:
```
$ ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
$ ruby test.rb
require 'tty-pager' failed with undefined method `gunzip' for Gem:Module

    INDEX = Marshal.load(Gem.gunzip(File.binread(INDEX_FILENAME)))
                            ^^^^^^^
require 'tty-table' failed with undefined method `gunzip' for Gem:Module

    INDEX = Marshal.load(Gem.gunzip(File.binread(INDEX_FILENAME)))
                            ^^^^^^^
```

### Actual behaviour

The Gem module doesn't have gunzip where it's expected.  If I use Ruby 3.0.0 it loads fine.

### Describe your environment

* OS version:  MacOS 12.2
* Ruby version: rvm installed rubies.  3.1.0 and 3.0.0
* TTY::Pager version:  0.7.1

**Comment by piotrmurach** [comment]
Hi Ed,

Thanks for trying out `tty-pager`.

The `tty` itself hasn't been updated in a while. Instead, please install different components directly. You can find the list at the [ttytoolkit.org](https://ttytoolkit.org).

As for `tty-pager`, you're trying to install an outdated `0.7.1` version. The latest is `0.14.0`. Please use this one, it's tested against Ruby `3.1`.
