### ISSUE TITLE
SystemPager raises error when executable is blank string

### ISSUE THREAD

**Issue by JacobEvelyn** [piotrmurach/tty-pager#5]
When the executable command passed in is an empty (`""`) or whitespace-only (`"  "`) string, the call to `TTY::Which` yields an error:

```
Failure/Error: TTY::Which.exist?(command)
     
     TypeError:
       no implicit conversion of nil into String
```

**Comment by piotrmurach** [comment]
Released `v0.7.1` with the patch.
