### ISSUE TITLE
Specify system pager?

### ISSUE THREAD

**Issue by JacobEvelyn** [piotrmurach/tty-pager#8]
As mentioned in [this comment](https://github.com/piotrmurach/tty-pager/pull/3#issuecomment-299453341) I'd like to be able to specify a specific system paging command to use (so it can use flags). Is there any movement on that feature being added?

**Comment by piotrmurach** [comment]
Hi Jacob, 

Sorry for being less responsive as I've been travelling across Europe and just returned from my trip to Krakow with my parents. I will look into this shortly!

**Comment by piotrmurach** [comment]
@JacobEvelyn I've added the [:command](https://github.com/piotrmurach/tty-pager#command) option. Both `TTY::Pager` and `SystemPager` understand this option. Would you mind checking out master branch? Once happy I will release new version.

**Comment by piotrmurach** [comment]
Released `v0.8.0` with this feature. Please give it a try and let me know how it works for you.

**Comment by piotrmurach** [comment]
@JacobEvelyn Released `v0.9.0` that provides rewritten `SystemPager` that works on Windows and jruby!
